CREATE TABLE USERS (
    ID       BIGINT NOT NULL IDENTITY,
    LOGIN_ID VARCHAR(20) NOT NULL,
    NAME     VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    CONSTRAINT USERS_UK UNIQUE (LOGIN_ID)
);

INSERT INTO USERS (LOGIN_ID, NAME, PASSWORD)
VALUES ('admin', '管理者', '$2a$08$BFB5TUdWD4woNScz4G0gBOwAPUTJ3ew8l7HrNbI.Fuz7O.tPs2laS'); -- password > admin
